begin;
do $test$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); rid uuid:=gen_random_uuid(); result jsonb; original_time timestamptz; owner_name text:=current_user;
begin
 insert into auth.users(id) values(a),(b);
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.create_profile('qa_'||substr(replace(a::text,'-',''),1,14),0);
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.create_profile('qa_'||substr(replace(b::text,'-',''),1,14),0);
 insert into private.player_access(user_id,is_admin) values(a,true) on conflict(user_id) do update set is_admin=true;
 perform public.reserve_ai_challenges(a,rid,'zen');
 perform public.finish_ai_challenges(a,rid,'ai','[{"title":"Pause effacée","intro":"Texte secret"},{"title":"Marche"},{"title":"Habitudes"}]');
 select created_at into original_time from private.ai_challenge_batches where id=rid;
 if to_regprocedure('public.admin_delete_ai_proposal(uuid,integer,text)') is null then raise exception 'Proposal deletion RPC missing';end if;
 if has_function_privilege('anon','public.admin_delete_ai_proposal(uuid,integer,text)','EXECUTE') or has_function_privilege('service_role','public.admin_delete_ai_proposal(uuid,integer,text)','EXECUTE') then raise exception 'Deletion ACL exposed';end if;
 execute 'set local role authenticated';
 begin perform public.admin_delete_ai_proposal(rid,0,'Pause effacée');raise exception 'Non-admin allowed';exception when others then if sqlerrm='Non-admin allowed' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform public.admin_delete_ai_proposal(rid,0,'wrong');raise exception 'Wrong confirmation allowed';exception when others then if sqlerrm='Wrong confirmation allowed' then raise;end if;end;
 begin perform public.admin_delete_ai_proposal(rid,-1,'Habitudes');raise exception 'Negative index allowed';exception when others then if sqlerrm='Negative index allowed' then raise;end if;end;
 result:=public.admin_delete_ai_proposal(rid,0,'Pause effacée');
 if result->0->'suggestions'->0<>'null'::jsonb or result->0->'suggestions'->1->>'title'<>'Marche' or jsonb_array_length(result->0->'suggestions')<>3 then raise exception 'Indexes moved';end if;
 if result::text like '%Texte secret%' then raise exception 'Deleted text leaked in history';end if;
 execute format('set local role %I',owner_name);
 result:=public.reserve_ai_challenges(a,rid,'zen');
 if (result->>'claimed')::boolean or result::text like '%Texte secret%' then raise exception 'Reserve leaked or reclaimed';end if;
 result:=public.finish_ai_challenges(a,rid,'ai','[{"title":"Resurrected"},{},{}]');
 if result->'suggestions'->0<>'null'::jsonb then raise exception 'Finish resurrected proposal';end if;
 execute 'set local role authenticated';
 perform public.admin_delete_ai_proposal(rid,null,'Lot zen · '||rid::text);
 if public.admin_ai_history()<>'[]'::jsonb then raise exception 'Deleted batch still in history';end if;
 execute format('set local role %I',owner_name);
 result:=public.reserve_ai_challenges(a,rid,'zen');
 if (result->>'claimed')::boolean or not (result->>'deleted')::boolean then raise exception 'Deleted batch replay allowed';end if;
 result:=public.finish_ai_challenges(a,rid,'ai','[{"title":"Resurrected"},{},{}]');
 if result->'suggestions'<>'[null,null,null]'::jsonb then raise exception 'Batch resurrected';end if;
 if not exists(select 1 from private.ai_challenge_batches where id=rid and created_at=original_time) then raise exception 'Quota reservation lost';end if;
 insert into private.ai_challenge_batches(id,actor_id,theme) select gen_random_uuid(),a,'zen' from generate_series(1,9);
 begin perform public.reserve_ai_challenges(a,gen_random_uuid(),'zen');raise exception 'Deletion reset daily quota';exception when others then if sqlerrm='Deletion reset daily quota' then raise;end if;end;
 if exists(select 1 from private.admin_audit where target_id=rid::text and reason like '%effacée%') then raise exception 'Deleted text leaked to audit';end if;
 raise notice 'AI proposal deletion, confirmations, redaction, replay and quota passed';
end $test$;
rollback;
