import type { CatalogItem } from "./game";
// Barèmes fictifs de gameplay, sans estimation médicale.
export const expandedCatalog: CatalogItem[] = [
  {
    id: "cocktail-light",
    label: "Cocktail léger / dilué",
    kind: "excess",
    unit: "cocktail",
    max_quantity: 5,
    coefficient: -25,
    daily_cap: 0,
    icon: "wine",
  },
  {
    id: "cocktail-strong",
    label: "Cocktail fort / sucré",
    kind: "excess",
    unit: "cocktail",
    max_quantity: 5,
    coefficient: -45,
    daily_cap: 0,
    icon: "wine",
  },
  {
    id: "spirit-shot",
    label: "Shot d’alcool fort",
    kind: "excess",
    unit: "shot",
    max_quantity: 5,
    coefficient: -30,
    daily_cap: 0,
    icon: "wine",
  },
  {
    id: "vegetables",
    label: "Légumes frais / salade composée",
    kind: "health",
    unit: "portion",
    max_quantity: 3,
    coefficient: 20,
    daily_cap: 60,
    icon: "leaf",
  },
  {
    id: "berries-nuts",
    label: "Fruits rouges ou noix",
    kind: "health",
    unit: "portion",
    max_quantity: 2,
    coefficient: 25,
    daily_cap: 50,
    icon: "leaf",
  },
  {
    id: "plant-meal",
    label: "Repas végétalisé riche en fibres",
    kind: "health",
    unit: "repas",
    max_quantity: 2,
    coefficient: 40,
    daily_cap: 80,
    icon: "leaf",
  },
  {
    id: "brisk-walk",
    label: "Marche rapide de 30 minutes",
    kind: "health",
    unit: "marche de 30 min",
    max_quantity: 2,
    coefficient: 90,
    daily_cap: 180,
    icon: "footprints",
  },
  {
    id: "short-nap",
    label: "Sieste courte de 15 à 25 minutes",
    kind: "health",
    unit: "sieste",
    max_quantity: 1,
    coefficient: 30,
    daily_cap: 30,
    icon: "moon",
  },
  {
    id: "restful-night",
    label: "Nuit réparatrice de 7 à 8 heures",
    kind: "health",
    unit: "nuit",
    max_quantity: 1,
    coefficient: 90,
    daily_cap: 90,
    icon: "moon",
  },
  {
    id: "calm-break",
    label: "Déconnexion / repos calme",
    kind: "health",
    unit: "pause de 30 min",
    max_quantity: 3,
    coefficient: 20,
    daily_cap: 60,
    icon: "leaf",
  },
  {
    id: "real-holiday",
    label: "Vacances / vraie coupure",
    kind: "health",
    unit: "journée",
    max_quantity: 1,
    coefficient: 180,
    daily_cap: 180,
    icon: "leaf",
  },
  {
    id: "standard-drink",
    label: "Verre de vin ou bière standard",
    kind: "excess",
    unit: "verre",
    max_quantity: 5,
    coefficient: -20,
    daily_cap: 0,
    icon: "wine",
  },
  {
    id: "sweet-cocktail",
    label: "Cocktail sucré (mojito, margarita)",
    kind: "excess",
    unit: "cocktail",
    max_quantity: 5,
    coefficient: -35,
    daily_cap: 0,
    icon: "wine",
  },
  {
    id: "heavy-meal",
    label: "Repas lourd (fast-food, friture)",
    kind: "excess",
    unit: "repas",
    max_quantity: 3,
    coefficient: -45,
    daily_cap: 0,
    icon: "pizza",
  },
  {
    id: "processed-meat",
    label: "Charcuterie / viande ultra-transformée",
    kind: "excess",
    unit: "portion",
    max_quantity: 3,
    coefficient: -30,
    daily_cap: 0,
    icon: "pizza",
  },
  {
    id: "stress-day",
    label: "Journée de stress intense",
    kind: "excess",
    unit: "journée",
    max_quantity: 1,
    coefficient: -180,
    daily_cap: 0,
    icon: "activity",
  },
  {
    id: "sleepless-night",
    label: "Nuit blanche ou sommeil inférieur à 5 h",
    kind: "excess",
    unit: "nuit",
    max_quantity: 1,
    coefficient: -150,
    daily_cap: 0,
    icon: "coffee",
  },
  {
    id: "cigarette",
    label: "Cigarette",
    kind: "excess",
    unit: "cigarette",
    max_quantity: 20,
    coefficient: -12,
    daily_cap: 0,
    icon: "flame",
  },
];
